### ISSUE TITLE
Re-structure myPageData hook

### ISSUE THREAD

**Issue by aziyatali** [ninetydays/kross-SDK#202]
as titled

**Comment by Jscripter-pk** [comment]
@aziyatali what is the purpose of this?

**Comment by aziyatali** [comment]
@Jscripter-pk  Currently we are using some properties of myPageData in several pages.
Issue arises let's say we need only totalAssets in /invest page. However, it will still fetch note-summary and other attr along the way which is in-efficient.

**Comment by Jscripter-pk** [comment]
@aziyatali then please create seperate function for that /invest page instead of updating already existing function as it was first created specifically for investor mobile app.
What you can do is that create a function that only calculate totalAssets/ return totalAssets and keep myPageData as it is otherwise it will lead to unmanaged issues across mobile and web version and I think @limhm1396 is also using it in kross-meta too.

**Comment by aziyatali** [comment]
@Jscripter-pk  kross-meta uses only native functions.
In terms of app, yeah, it makes sense but somehow we need still to refactor upcoming days and come up with the better structure that won't hurt performance.

**Comment by Jscripter-pk** [comment]
@aziyatali yeah it better to do that once other things get aligned well for us.
